-- AlterTable
ALTER TABLE "ProductImage" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "sequence" SET DATA TYPE INTEGER,
ALTER COLUMN "image" SET DATA TYPE TEXT;
